### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AyushSagpariya** [xenon-19/Gesture-Controlled-Virtual-Mouse#15]
Can you help me to solve this error?

![Screenshot 2022-05-31 110732](https://user-images.githubusercontent.com/72784559/171137143-3a9a57b9-3d68-4233-bda0-597bb9ea7782.png)

**Comment by ankit-4129** [comment]
I think eel is not able to find exposed function `addAppMsg()` in javascript on line https://github.com/xenon-19/Gesture-Controlled-Virtual-Mouse/blob/a275d9d107f11d199d743b4dbfa467977439ed3b/src/web/js/main.js#L27

Run eel hello world [01 - hello_world](https://github.com/ChrisKnott/Eel/tree/master/examples/01%20-%20hello_world) and share the output.

**Comment by AyushSagpariya** [comment]
![Screenshot 2022-05-31 135208](https://user-images.githubusercontent.com/72784559/171166811-67a9ee28-0d1f-4ce0-a0d6-ec2d464d7826.png)

**Comment by ankit-4129** [comment]
your issue is related to eel module.

Q1. When you execute `hello.py` is there any application opening(see below image)?
![image](https://user-images.githubusercontent.com/77689685/171168234-ebd2a1ba-4262-4035-b502-ac49852f8061.png)

Q2. Have you downloaded `web` folder along with `hello.py` from [01 - hello_world](https://github.com/ChrisKnott/Eel/tree/master/examples/01%20-%20hello_world) and kept them in same folder? (See below image, keep files in this structure).
![image](https://user-images.githubusercontent.com/77689685/171169982-4ee479e6-6e79-4a79-a810-621d7335b247.png)

Try to run `hello.py` using CMD.

**Comment by AyushSagpariya** [comment]
Yes, check it there is still the same error.

**Comment by ankit-4129** [comment]
I am not sure about this issue your are facing while running eel hello world example, you should go through eel readme https://github.com/ChrisKnott/Eel and try to run baisc example, you can open a issue there for the same.
